# Generated by Django 5.2.8 on 2025-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_category_alter_plant_image_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flag', models.ImageField(upload_to='plants/images/')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(to='plant.country'),
        ),
    ]
